export const siteLocales = ['en', 'fr'] as const

export type SiteLocale = (typeof siteLocales)[number]

export function isSiteLocale(value: string): value is SiteLocale {
  return siteLocales.includes(value as SiteLocale)
}

export function normalizeSiteLocale(value?: string): SiteLocale {
  return value === 'fr' ? 'fr' : 'en'
}

export function getSiteDateLocale(locale: string): string {
  return locale === 'fr' ? 'fr-CA' : 'en-CA'
}

export const uiCopy = {
  en: {
    navbar: {
      donate: 'Support Us',
      mobileDonate: 'Support Our Mission',
      viewPage: 'View Page',
      switchTo: 'Switch language to {language}',
      switchLanguage: 'French',
      languageLabel: 'Language',
      english: 'English',
      french: 'French',
      mainNavigation: 'Main navigation',
      mobileNavigation: 'Mobile navigation',
      homeAria: 'Home - Mulenge Scholars Network Canada',
      logoAlt: 'Mulenge Scholars Network Canada emblem',
      mobileMenuOpen: 'Open main menu',
      mobileMenuClose: 'Close main menu',
      emailUs: 'Email us',
      exploreFallback: 'Explore',
      copyright: 'Copyright 2026 MSNC Canada',
      nav: [
        {
          id: '01',
          name: 'About',
          href: '/about',
          tagline: 'Legacy & Vision',
          desc: 'Redefining educational pathways for global scholars.',
        },
        {
          id: '02',
          name: 'Programs',
          href: '/programs',
          tagline: 'Core Pillars',
          desc: 'Specialized support tracks from bridging to adult learning.',
        },
        {
          id: '03',
          name: 'Impact',
          href: '/impact/rebuilding-futures',
          tagline: 'Real Results',
          desc: 'Success stories from our global community.',
        },
        {
          id: '04',
          name: 'Journal',
          href: '/blog',
          tagline: 'Latest Insights',
          desc: 'Research, updates, and leadership pieces.',
        },
        {
          id: '05',
          name: 'Contact',
          href: '/contact',
          tagline: 'Get Involved',
          desc: 'Connect for partnerships or volunteering.',
        },
      ],
      megaMenu: [
        {
          id: 'who-we-are',
          label: 'Who We Are',
          tagline: 'Our identity',
          desc: 'Learn about the people, values, and purpose that define Mulenge Scholars Network Canada.',
          accentColor: '#185FA5',
          items: [
            { id: 'about', label: 'About Us', href: '/about', desc: 'Our story, values, and vision for the community.' },
            { id: 'mission', label: 'Mission & Vision', href: '/about#mission', desc: 'The principles that guide everything we do.' },
            { id: 'leadership', label: 'Leadership & Team', href: '/leadership', desc: 'Meet the dedicated people behind MSNC.' },
            { id: 'impact', label: 'Our Impact', href: '/impact/rebuilding-futures', desc: 'See the difference we make together.' },
          ],
        },
        {
          id: 'what-we-do',
          label: 'What We Do',
          tagline: 'Programs & initiatives',
          desc: 'Discover programs that empower newcomers and build lasting pathways to belonging.',
          accentColor: '#0F6E56',
          items: [
            { id: 'programs', label: 'Our Programs', href: '/programs', desc: 'An overview of all our community initiatives.' },
            { id: 'adult-learning', label: 'Adult Learning', href: '/programs/adult-learning', desc: 'Bridging skills gaps for newcomer adults.' },
            { id: 'high-school', label: 'High School Support', href: '/programs/high-school-support', desc: 'Academic guidance and support for high school students.' },
            { id: 'workshops', label: 'Workshops & Community', href: '/programs/workshops-community', desc: 'Community workshops and engagement programs.' },
          ],
        },
        {
          id: 'community',
          label: 'Community',
          tagline: 'Stay connected',
          desc: 'Stay in the loop with events, stories, and news from across our network.',
          accentColor: '#854F0B',
          items: [
            { id: 'events', label: 'Events', href: '/events', desc: 'Upcoming gatherings, workshops, and celebrations.' },
            { id: 'blog', label: 'News & Stories', href: '/blog', desc: 'Insights, updates, and community highlights.' },
          ],
        },
        {
          id: 'get-involved',
          label: 'Get Involved',
          tagline: 'Take action',
          desc: 'Your involvement makes a difference. Join us, volunteer, or simply reach out.',
          accentColor: '#7C2D12',
          items: [
            { id: 'join', label: 'Join the Network', href: '/join', desc: 'Become a member and grow with us.' },
            { id: 'contact', label: 'Contact Us', href: '/contact', desc: 'Reach out — we’d love to hear from you.' },
          ],
        },
      ],
    },
    footer: {
      brand: 'Empowering Mulenge diaspora youth through education, mentorship, and leadership for sustainable futures.',
      primaryHeading: 'MSNC',
      actionsHeading: 'Actions',
      contactHeading: 'Get in touch',
      newsletterHeading: 'Newsletter',
      newsletterBody: 'Stay updated with program launches and impact stories.',
      newsletterSubject: 'Newsletter Signup',
      newsletterName: 'Newsletter Subscriber',
      newsletterMessage: 'Please add this email address to the MSNC newsletter list.',
      newsletterPlaceholder: 'your@email.com',
      newsletterAria: 'Email for newsletter',
      newsletterCta: 'Subscribe',
      socialInstagram: 'Instagram',
      logoAlt: 'Mulenge Scholars Network Canada logo',
      legal: {
        privacy: 'Privacy',
        terms: 'Terms',
        sitemap: 'Sitemap',
      },
      rights: "Copyright {year} Mulenge Scholars' Network Canada. All rights reserved.",
      navLinks: [
        { name: 'About', href: '/about' },
        { name: 'Programs', href: '/programs' },
        { name: 'Events', href: '/events' },
        { name: 'Leadership', href: '/leadership' },
      ],
      actionLinks: [
        { name: 'Join', href: '/join' },
        { name: 'Donate', href: '/donate' },
        { name: 'Blog', href: '/blog' },
        { name: 'Contact', href: '/contact' },
      ],
      contactInfo: {
        email: { label: 'Email', value: 'info@mulengescholars.org' },
        location: { label: 'Locations', value: 'Canada' },
      },
    },
    hero: {
      country: 'Canada',
      commitmentLabel: 'I. The Commitment',
      commitmentLead:
        'We are dedicated to empowering youth across Canada through mentorship, academic guidance, and leadership development.',
      commitmentBody:
        'By fostering a strong sense of community and belonging, we bridge the gap between migration and scholarly success.',
      learnMore: 'Learn More',
      programs: 'Our Programs',
      heritageLabel: 'II. Heritage',
      heritageBody:
        'Founded by Banyamulenge students, MSNC carries the legacy of the highlands, transforming a history of migration and resilience into a catalyst for professional growth.',
      tags: ['Mentorship', 'Equity', 'Leadership', 'Excellence'],
      visionLabel: 'III. The Vision',
      visionQuote:
        'A future where our youth are successful in their academic journeys and established as leaders giving back to their communities.',
      principles: 'Our Guiding Principles',
      principlesValue: 'Equity & Excellence',
    },
pages: {
      strategySummary: 'Our Strategy & Programs',
      upcomingEvents: 'Upcoming Events',
      networkLabel: 'Our Network',
      networkHeading: 'Trusted By Global Institutions',
      events: {
        label: 'Calendar',
        title: 'Events',
        description: 'Documenting the movement of scholars across disciplines, borders, and leadership summits.',
        breadcrumb: 'Events',
        upcoming: 'Upcoming Events',
        past: 'Past Events',
        noUpcoming: 'No Upcoming Events Registered',
        viewDetails: 'View Event Details',
        upcomingBadge: 'Upcoming',
        backToEvents: 'Back to Chronicles Repository',
        status: 'Status: Documented',
        logRef: 'LOG_REF_ID:',
        voicesTitle: 'Voices from the Summit',
        verifiedAttendee: 'Verified Attendee',
        reflectionLedger: 'Post-Event Reflection Ledger',
        visualRecord: 'Visual_Record',
        artifactPhotography: 'Artifact_Field_Photography',
        securedRecord: 'Secured Record',
        archives: 'Archives',
        register: 'Register',
        relatedEvents: 'Related Events',
        ctaTitle: 'Explore all our events',
      },
    },
  },
  fr: {
    navbar: {
      donate: 'Nous soutenir',
      mobileDonate: 'Soutenir notre mission',
      viewPage: 'Voir la page',
      switchTo: 'Changer la langue en {language}',
      switchLanguage: 'Anglais',
      languageLabel: 'Langue',
      english: 'Anglais',
      french: 'Français',
      mainNavigation: 'Navigation principale',
      mobileNavigation: 'Navigation mobile',
      homeAria: 'Accueil - Réseau des Boursiers de Mulenge Canada',
      logoAlt: 'Emblème du Réseau des Boursiers de Mulenge Canada',
      mobileMenuOpen: 'Ouvrir le menu principal',
      mobileMenuClose: 'Fermer le menu principal',
      emailUs: 'Nous écrire',
      exploreFallback: 'Explorer',
      copyright: 'Copyright 2026 MSNC Canada',
      nav: [
        {
          id: '01',
          name: 'À propos',
          href: '/about',
          tagline: 'Héritage et vision',
          desc: 'Redéfinir les parcours éducatifs pour les boursiers de la diaspora.',
        },
        {
          id: '02',
          name: 'Programmes',
          href: '/programs',
          tagline: 'Piliers clés',
          desc: "Des parcours d'accompagnement spécialisés, du soutien scolaire à la formation des adultes.",
        },
        {
          id: '03',
          name: 'Impact',
          href: '/impact/rebuilding-futures',
          tagline: 'Résultats concrets',
          desc: 'Des histoires de réussite au sein de notre communauté mondiale.',
        },
        {
          id: '04',
          name: 'Journal',
          href: '/blog',
          tagline: 'Dernières réflexions',
          desc: 'Recherches, actualités et prises de parole du leadership.',
        },
        {
          id: '05',
          name: 'Contact',
          href: '/contact',
          tagline: "S'impliquer",
          desc: 'Échangez avec nous pour un partenariat ou du bénévolat.',
        },
      ],
      megaMenu: [
        {
          id: 'who-we-are',
          label: 'Qui Nous Sommes',
          tagline: 'Notre identité',
          desc: 'Découvrez les personnes, les valeurs et l\'objectif qui définissent le Réseau des Boursiers de Mulenge Canada.',
          accentColor: '#185FA5',
          items: [
            { id: 'about', label: 'À Propos', href: '/about', desc: 'Notre histoire, nos valeurs et notre vision pour la communauté.' },
            { id: 'mission', label: 'Mission & Vision', href: '/about#mission', desc: 'Les principes qui guident tout ce que nous faisons.' },
            { id: 'leadership', label: 'Leadership & Équipe', href: '/leadership', desc: 'Rencontrez les personnes dévouées derrière le MSNC.' },
            { id: 'impact', label: 'Notre Impact', href: '/impact/rebuilding-futures', desc: 'Voyez la différence que nous faisons ensemble.' },
          ],
        },
        {
          id: 'what-we-do',
          label: 'Nos Actions',
          tagline: 'Programmes & initiatives',
          desc: 'Découvrez les programmes qui autonomisent les nouveaux arrivants et créent des voies durables d\'intégration.',
          accentColor: '#0F6E56',
          items: [
            { id: 'programs', label: 'Nos Programmes', href: '/programs', desc: 'Un aperçu de toutes nos initiatives communautaires.' },
            { id: 'adult-learning', label: 'Apprentissage Adulte', href: '/programs/adult-learning', desc: 'Combler les lacunes en matière de compétences pour les adultes.' },
            { id: 'high-school', label: 'Soutien au Lycée', href: '/programs/high-school-support', desc: 'Orientation et soutien scolaire pour les élèves du secondaire.' },
            { id: 'workshops', label: 'Ateliers & Communauté', href: '/programs/workshops-community', desc: 'Ateliers communautaires et programmes d\'engagement.' },
          ],
        },
        {
          id: 'community',
          label: 'Communauté',
          tagline: 'Restez connecté',
          desc: 'Restez informé des événements, des histoires et des actualités de notre réseau.',
          accentColor: '#854F0B',
          items: [
            { id: 'events', label: 'Événements', href: '/events', desc: 'Rassemblements à venir, ateliers et célébrations.' },
            { id: 'blog', label: 'Nouvelles & Histoires', href: '/blog', desc: 'Aperçus, mises à jour et faits saillants de la communauté.' },
          ],
        },
        {
          id: 'get-involved',
          label: 'S\'impliquer',
          tagline: 'Passez à l\'action',
          desc: 'Votre implication fait la différence. Rejoignez-nous, faites du bénévolat ou contactez-nous.',
          accentColor: '#7C2D12',
          items: [
            { id: 'join', label: 'Rejoindre le Réseau', href: '/join', desc: 'Devenez membre et grandissez avec nous.' },
            { id: 'contact', label: 'Contactez-nous', href: '/contact', desc: 'Écrivez-nous — nous serions ravis d\'échanger avec vous.' },
          ],
        },
      ],
    },
    footer: {
      brand:
        "Renforcer les jeunes de la diaspora mulenge par l'éducation, le mentorat et le leadership pour un avenir durable.",
      primaryHeading: 'MSNC',
      actionsHeading: 'Actions',
      contactHeading: 'Nous joindre',
      newsletterHeading: 'Infolettre',
      newsletterBody: "Recevez nos nouveautés sur les programmes et les histoires d'impact.",
      newsletterSubject: "Inscription à l'infolettre",
      newsletterName: "Abonné à l'infolettre",
      newsletterMessage: "Veuillez ajouter cette adresse courriel à la liste de diffusion du MSNC.",
      newsletterPlaceholder: 'votre@email.com',
      newsletterAria: "Courriel pour l'infolettre",
      newsletterCta: "S'abonner",
      socialInstagram: 'Instagram',
      logoAlt: 'Logo du Réseau des Boursiers de Mulenge Canada',
      legal: {
        privacy: 'Confidentialité',
        terms: 'Conditions',
        sitemap: 'Plan du site',
      },
      rights: 'Copyright {year} Réseau des Boursiers Mulenge Canada. Tous droits réservés.',
      navLinks: [
        { name: 'À propos', href: '/about' },
        { name: 'Programmes', href: '/programs' },
        { name: 'Événements', href: '/events' },
        { name: 'Leadership', href: '/leadership' },
      ],
      actionLinks: [
        { name: 'Rejoindre', href: '/join' },
        { name: 'Donner', href: '/donate' },
        { name: 'Journal', href: '/blog' },
        { name: 'Contact', href: '/contact' },
      ],
      contactInfo: {
        email: { label: 'Courriel', value: 'info@mulengescholars.org' },
        location: { label: 'Présence', value: 'Canada' },
      },
    },
    hero: {
      country: 'Canada',
      commitmentLabel: 'I. Notre engagement',
      commitmentLead:
        "Nous nous engageons à accompagner les jeunes à travers le Canada par le mentorat, l'orientation scolaire et le développement du leadership.",
      commitmentBody:
        "En renforçant le sentiment d'appartenance et de communauté, nous comblons l'écart entre migration et réussite scolaire.",
      learnMore: 'En savoir plus',
      programs: 'Nos programmes',
      heritageLabel: 'II. Héritage',
      heritageBody:
        "Fondé par des étudiants banyamulenge, le MSNC porte l'héritage des hauts plateaux et transforme une histoire de migration et de résilience en moteur de progression professionnelle.",
      tags: ['Mentorat', 'Équité', 'Leadership', 'Excellence'],
      visionLabel: 'III. La vision',
      visionQuote:
        'Un avenir où nos jeunes réussissent leur parcours scolaire et deviennent des leaders qui redonnent à leurs communautés.',
      principles: 'Nos principes directeurs',
      principlesValue: 'Équité et excellence',
    },
pages: {
      strategySummary: 'Notre stratégie et nos programmes',
      upcomingEvents: 'Événements à venir',
      networkLabel: 'Notre réseau',
      networkHeading: 'La confiance des institutions mondiales',
      events: {
        label: 'Calendrier',
        title: 'Événements',
        description: 'Documenter le parcours des boursiers à travers les disciplines, les frontières et les sommets de leadership.',
        breadcrumb: 'Événements',
        upcoming: 'Événements à venir',
        past: 'Événements passés',
        noUpcoming: 'Aucun événement à venir enregistré',
        viewDetails: 'Voir les détails',
        upcomingBadge: 'À venir',
        backToEvents: 'Retour au répertoire',
        status: 'Statut: Documenté',
        logRef: 'ID_RÉF:',
        voicesTitle: 'Voix du Sommet',
        verifiedAttendee: 'Participant vérifié',
        reflectionLedger: 'Registre de réflexion',
        visualRecord: 'Enregistrement visuel',
        artifactPhotography: 'Photographie Artifact',
        securedRecord: 'Enregistrement sécurisé',
        archives: 'Archives',
        register: "S'inscrire",
        relatedEvents: 'Événements liés',
        ctaTitle: 'Explorez tous nos événements',
      },
    },
  },
} as const

export function getUiCopy(locale: string) {
  return uiCopy[normalizeSiteLocale(locale)]
}
